=== aerix-nl/nota-invoice-template/json/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://aerix.nl/invoice-schema",
  "type": "object",
  "properties": {
    "meta": {
      "id": "http://aerix.nl/invoice-schema/meta",
      "type": "object",
      "properties": {
        "period": {
          "id": "http://aerix.nl/invoice-schema/meta/period",
          "type": "integer",
          "minimum": 0
        },
        "type": {
          "id": "http://aerix.nl/invoice-schema/meta/type",
          "type": "string",
          "pattern": "quotation|invoice"
        },
        "date": {
          "id": "http://aerix.nl/invoice-schema/meta/date",
          "type": "string",
          "pattern": "\\d{4}(?:-\\d?\\d){2}"
        },
        "id": {
          "id": "http://aerix.nl/invoice-schema/meta/id",
          "type": "integer",
          "minimum": 0
        }
      },
      "required": [
        "id",
        "date"
      ]
    },
    "origin": {
      "id": "http://aerix.nl/invoice-schema/origin",
      "type": "object",
      "properties": {
        "company": {
          "id": "http://aerix.nl/invoice-schema/origin/company",
          "type": "string"
        },
        "lawform": {
          "id": "http://aerix.nl/invoice-schema/origin/lawform",
          "type": "string"
        },
        "address": {
          "id": "http://aerix.nl/invoice-schema/origin/address",
          "type": "string"
        },
        "postalcode": {
          "id": "http://aerix.nl/invoice-schema/origin/postalcode",
          "type": "string",
          "pattern": "\\d{4}\\s?[A-z]{2}"
        },
        "town": {
          "id": "http://aerix.nl/invoice-schema/origin/town",
          "type": "string"
        },
        "country": {
          "id": "http://aerix.nl/invoice-schema/origin/country",
          "type": "string"
        },
        "email": {
          "id": "http://aerix.nl/invoice-schema/origin/email",
          "type": "string"
        },
        "website": {
          "id": "http://aerix.nl/invoice-schema/origin/website",
          "type": "string"
        },
        "iban": {
          "id": "http://aerix.nl/invoice-schema/origin/iban",
          "type": "string"
        },
        "bank": {
          "id": "http://aerix.nl/invoice-schema/origin/bank",
          "type": "string"
        },
        "bic": {
          "id": "http://aerix.nl/invoice-schema/origin/bic",
          "type": "string"
        },
        "kvk": {
          "id": "http://aerix.nl/invoice-schema/origin/kvk",
          "type": "string"
        },
        "vat": {
          "id": "http://aerix.nl/invoice-schema/origin/vat",
          "type": "string"
        }
      },
      "required": [
        "company",
        "lawform",
        "address",
        "postalcode",
        "town",
        "country",
        "email",
        "website",
        "iban",
        "bank",
        "bic",
        "kvk",
        "vat"
      ]
    },
    "validityPeriod": {
      "id": "http://aerix.nl/invoice-schema/validityPeriod",
      "type": "integer"
    },
    "vatPercentage": {
      "id": "http://aerix.nl/invoice-schema/vatPercentage",
      "type": "number",
      "minimum": 0,
      "maximum": 1
    },
    "currencySymbol": {
      "id": "http://aerix.nl/invoice-schema/currencySymbol",
      "type": "string"
    },
    "client": {
      "id": "http://aerix.nl/invoice-schema/client",
      "type": "object",
      "properties": {
        "organization": {
          "id": "http://aerix.nl/invoice-schema/client/organization",
          "type": "string"
        },
        "contactPerson": {
          "id": "http://aerix.nl/invoice-schema/client/contactPerson",
          "type": "string"
        },
        "address": {
          "id": "http://aerix.nl/invoice-schema/client/address",
          "type": "string"
        },
        "postalcode": {
          "id": "http://aerix.nl/invoice-schema/client/postalcode",
          "type": "string"
        },
        "town": {
          "id": "http://aerix.nl/invoice-schema/client/town",
          "type": "string"
        },
        "country": {
          "id": "http://aerix.nl/invoice-schema/client/country",
          "type": "string"
        }
      },
      "required": [
        "organization"
      ]
    },
    "projectName": {
      "id": "http://aerix.nl/invoice-schema/projectName",
      "type": "string"
    },
    "invoiceItems": {
      "id": "http://aerix.nl/invoice-schema/invoiceItems",
      "type": "array",
      "items": {
        "id": "http://aerix.nl/invoice-schema/invoiceItems/item",
        "type": "object",
        "properties": {
          "description": {
            "id": "http://aerix.nl/invoice-schema/invoiceItems/regular/description",
            "type": "string"
          },
          "quantity": {
            "id": "http://aerix.nl/invoice-schema/invoiceItems/regular/quantity",
            "type": "number",
            "minimum": 1
          },
          "price": {
            "id": "http://aerix.nl/invoice-schema/invoiceItems/regular/price",
            "type": "number",
            "minimum": 0
          },
          "type": {
            "id": "http://aerix.nl/invoice-schema/invoiceItems/regular/type",
            "type": "string",
            "pattern": "product|service"
          },
          "discount": {
            "id": "http://aerix.nl/invoice-schema/invoiceItems/regular/discount",
            "type": "number",
            "minimum": 0
          }
        },
        "required": [
          "description",
          "quantity",
          "price"
        ]
      }
    }
  },
  "required": [
    "meta",
    "origin",
    "validityPeriod",
    "vatPercentage",
    "currencySymbol",
    "client",
    "projectName",
    "invoiceItems"
  ]
}

=== aerix-nl/nota-invoice-template/json/preview.json
{
  "meta": {
    "id": 15,
    "period": 3,
    "date": "2013-12-25"
  },
  "origin": {
    "company": "YourCompany",
    "lawform": "Ltd.",
    "address": "Your Street 13b",
    "postalcode": "0987KJ",
    "town": "Yourtown",
    "country": "Your Country",
    "email": "contact@mycompany.com",
    "website": "mycompany.com",
    "iban": "NL12 ABCD 1234 1234 12",
    "bank": "Triodos Bank",
    "bic": "RABONL2U",
    "kvk": "123456789",
    "vat": "AB1233405923489"
  },
  "validityPeriod": 14,
  "vatPercentage": 0.21,
  "currencySymbol": "â‚¬",
  "client": {
    "organization": "Client Company Name",
    "contactPerson": "Client Contactperson Name",
    "address": "Client Street 11a",
    "postalcode": "6543TR",
    "town": "Client Town",
    "country": "Netherlands, The"
  },
  "projectName": "Optional project name which will be placed on top of table",
  "invoiceItems": [
    {
      "description": "Service string",
      "quantity": 1,
      "price": 203.23
    }, {
      "description": "Product string",
      "quantity": 14,
      "price": 10,
      "discount": 0.1
    }
  ]
}
